export const WEEK_1_CONFIG = {
    weekNumber: 1,
    label: "Week 1",
    imagePath: "/week-1.png",
    seed: 2025,
    gridSize: 12,
    // Set exact open/close times when the schedule is confirmed, e.g.:
    // startsAt: "2026-06-24T00:00:00+05:30",
    // endsAt: "2026-06-30T23:59:59+05:30",
    startsAt: null,
    endsAt: null,
    words: [
        {
            id: "w1",
            word: "KEYBOARD",
            clue: "I have many keys but open no doors. Without me, your ideas stay locked away.",
            direction: "across",
            number: 1,
        },
        {
            id: "w2",
            word: "EMAIL",
            clue: "I travel across departments in seconds. Yet I never leave my desk.",
            direction: "across",
            number: 2,
        },
        {
            id: "w3",
            word: "EXCEL",
            clue: "I have many pages but no story. Numbers are my favorite language.",
            direction: "across",
            number: 3,
        },
        {
            id: "w4",
            word: "WIFI",
            clue: "I connect everyone in the office. You'll miss me only when I'm gone.",
            direction: "down",
            number: 4,
        },
        {
            id: "w5",
            word: "BROWSER",
            clue: "I can have dozens of tabs. Yet I'm not a notebook.",
            direction: "down",
            number: 5,
        },
        {
            id: "w6",
            word: "CALENDAR",
            clue: "The more meetings I create, the less people like me. Still, they check me every day.",
            direction: "across",
            number: 6,
        },
        {
            id: "w7",
            word: "PRINTER",
            clue: "I work silently until someone asks me to do everything at once. Then everyone blames me for being slow.",
            direction: "down",
            number: 7,
        },
        {
            id: "w8",
            word: "FINDER",
            clue: "I know where every file lives. But I never open one on my own.",
            direction: "down",
            number: 8,
        },
        {
            id: "w9",
            word: "PASSWORD",
            clue: "You trust me with your secrets every day. But you only remember me when you forget me.",
            direction: "across",
            number: 9,
        },
        {
            id: "w10",
            word: "DOCUMENT",
            clue: "I can be shared with hundreds of people. But only one wrong click can change everything.",
            direction: "across",
            number: 10,
        },
    ],
};
