export const WEEK_2_CONFIG = {
    weekNumber: 2,
    label: "Week 2",
    imagePath: "/week-2.png",
    seed: 2027,
    gridSize: 12,
    startsAt: "2026-07-17T00:00:00+05:30",
    endsAt: "2026-07-23T23:59:59+05:30",
    words: [
        {
            id: "w2-1",
            word: "NOTEBOOK",
            clue: "I hold your ideas one page at a time. Yet I never complain when you erase them.",
            direction: "across",
            number: 11,
        },
        {
            id: "w2-2",
            word: "PAPERCLIP",
            clue: "I quietly hold papers together. Though I'm small, I keep everything in place.",
            direction: "across",
            number: 12,
        },
        {
            id: "w2-3",
            word: "PEN",
            clue: "People borrow me every day. Somehow, I never find my way back.",
            direction: "down",
            number: 13,
        },
        {
            id: "w2-4",
            word: "ERASER",
            clue: "I erase your mistakes without saying a word. But I can't fix them once they're printed.",
            direction: "across",
            number: 14,
        },
        {
            id: "w2-5",
            word: "COFFEEMUG",
            clue: "I'm always full before a meeting. By the end, I'm completely empty.",
            direction: "down",
            number: 15,
        },
        {
            id: "w2-6",
            word: "PHOTOCOPIER",
            clue: "I make exact copies in seconds. Every page I create looks exactly like the last.",
            direction: "across",
            number: 16,
        },
        {
            id: "w2-7",
            word: "ZIPFILE",
            clue: "I shrink large files without losing a thing. I'm often used before sharing.",
            direction: "down",
            number: 17,
        },
        {
            id: "w2-8",
            word: "USBDRIVE",
            clue: "I carry thousands of documents. Yet I fit comfortably in your pocket.",
            direction: "down",
            number: 18,
        },
        {
            id: "w2-9",
            word: "STICKYNOTE",
            clue: "I'm usually bright yellow. I remind you of things you'd otherwise forget.",
            direction: "across",
            number: 19,
        },
        {
            id: "w2-10",
            word: "REFRIGERATOR",
            clue: "I hold your lunch until you're ready. But I never take a bite.",
            direction: "across",
            number: 20,
        },
    ],
};
