export const WEEK_4_CONFIG = {
    weekNumber: 4,
    label: "Week 4",
    imagePath: "/week-4.png",
    seed: 2029,
    gridSize: 14,
    startsAt: "2026-08-03T00:00:00+05:30",
    endsAt: "2026-08-09T23:59:59+05:30",
    words: [
        {
            id: "w4-1",
            word: "BLUETOOTH",
            clue: "I connect nearby devices without using a single wire.",
            direction: "across",
            number: 31,
        },
        {
            id: "w4-2",
            word: "MICROFIBER",
            clue: "I clean your screen without scratching it. Yet I'm not a cleaning spray.",
            direction: "across",
            number: 32,
        },
        {
            id: "w4-3",
            word: "SIGNBOARD",
            clue: "I tell visitors where to go. Yet I never move from my place.",
            direction: "down",
            number: 33,
        },
        {
            id: "w4-4",
            word: "SHREDDER",
            clue: "I destroy confidential papers so they can never be read again.",
            direction: "across",
            number: 34,
        },
        {
            id: "w4-5",
            word: "CHARGER",
            clue: "I'm attached to your computer most of the day. Without me, your battery won't last long.",
            direction: "down",
            number: 35,
        },
        {
            id: "w4-6",
            word: "HEADPHONES",
            clue: "I help you hear every meeting clearly. Yet I never say a word.",
            direction: "across",
            number: 36,
        },
        {
            id: "w4-7",
            word: "AIRCONDITIONER",
            clue: "I keep the office comfortable in every season. People notice me only when I stop working.",
            direction: "down",
            number: 37,
        },
        {
            id: "w4-8",
            word: "AUTOSAVE",
            clue: "I save your work in the background. Most people notice me only when I'm missing.",
            direction: "across",
            number: 38,
        },
        {
            id: "w4-9",
            word: "ELEVATOR",
            clue: "I move people between floors all day. Yet I never leave the building.",
            direction: "down",
            number: 39,
        },
        {
            id: "w4-10",
            word: "RECEPTION",
            clue: "I welcome every visitor before anyone else does. I stand at the entrance all day.",
            direction: "across",
            number: 40,
        },
    ],
};
