export const WEEK_3_CONFIG = {
    weekNumber: 3,
    label: "Week 3",
    imagePath: "/week-3.png",
    seed: 2028,
    gridSize: 12,
    startsAt: "2026-07-24T00:00:00+05:30",
    endsAt: "2026-07-30T23:59:59+05:30",
    words: [
        {
            id: "w3-1",
            word: "WHITEBOARD",
            clue: "People write on me during meetings. A few minutes later, I'm completely clean again.",
            direction: "across",
            number: 21,
        },
        {
            id: "w3-2",
            word: "MARKER",
            clue: "I bring color to ideas. But if you forget me, I'll dry out.",
            direction: "across",
            number: 22,
        },
        {
            id: "w3-3",
            word: "UPS",
            clue: "I hide beneath your desk most of the time. You'll appreciate me most during a power outage.",
            direction: "down",
            number: 23,
        },
        {
            id: "w3-4",
            word: "DESKLAMP",
            clue: "I brighten your workspace without making a sound. When I stop, everyone notices.",
            direction: "down",
            number: 24,
        },
        {
            id: "w3-5",
            word: "CLOCK",
            clue: "I know the time of every meeting. Yet I've never attended one.",
            direction: "across",
            number: 25,
        },
        {
            id: "w3-6",
            word: "DRAWER",
            clue: "I keep your desk organized. Open me, and you'll find what you've been looking for.",
            direction: "down",
            number: 26,
        },
        {
            id: "w3-7",
            word: "BINDER",
            clue: "I organize papers into neat sections. Without me, documents quickly become messy.",
            direction: "across",
            number: 27,
        },
        {
            id: "w3-8",
            word: "FOLDER",
            clue: "I keep important papers together while protecting them from damage.",
            direction: "down",
            number: 28,
        },
        {
            id: "w3-9",
            word: "IDCARD",
            clue: "I protect your identity at work. Without me, some doors stay closed.",
            direction: "across",
            number: 29,
        },
        {
            id: "w3-10",
            word: "ITSUPPORT",
            clue: "I'm the first person people call when technology stops cooperating. Everyone knows my name only when something goes wrong.",
            direction: "across",
            number: 30,
        },
    ],
};
